http:
  middlewares:
    cors:
      headers:
        accessControlAllowOriginList:
          - "http://localhost:5173"
        accessControlAllowMethods:
          - "GET"
          - "POST"
          - "PUT"
          - "PATCH"
          - "DELETE"
          - "OPTIONS"
        accessControlAllowHeaders:
          - "Content-Type"
          - "Authorization"
        accessControlMaxAge: 86400

    security-headers:
      headers:
        contentTypeNosniff: true
        frameDeny: true
        browserXssFilter: true